version: "3.8"

services:
  grafana:
    image: "grafana/grafana:9.1.8"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:2.6.1"
    ports:
      - "3100:3100"

  python-requests:
    image: "jvelascoiti/python-requests:1.0"
    volumes:
      - ./scripts/:/scripts/